### ISSUE TITLE
Crash - java.lang.IllegalArgumentException: Duplicate id value for 13! after ladysnake.illuminations.entity.FireFlyEntity.func_70088_a

### ISSUE THREAD

**Issue by Stormwind99** [Ladysnake/Illuminations-for-Forge#5]
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 4/13/20 9:20 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Duplicate id value for 13!
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:83) ~[?:?] {re:classloading}
	at ladysnake.illuminations.entity.FireFlyEntity.func_70088_a(FireFlyEntity.java:64) ~[?:1.0.0.0] {re:classloading}
	at net.minecraft.entity.Entity.<init>(Entity.java:219) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision}
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:192) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at ladysnake.illuminations.entity.LightOrbEntity.<init>(LightOrbEntity.java:18) ~[?:1.0.0.0] {re:classloading}
	at ladysnake.illuminations.entity.FireFlyEntity.<init>(FireFlyEntity.java:49) ~[?:1.0.0.0] {re:classloading}
	at ladysnake.illuminations.block.FireFlyBlockTick.tick(FireFlyBlockTick.java:36) ~[?:1.0.0.0] {re:classloading}
	at ladysnake.illuminations.block.FireFlyTallGrassBlock.func_196267_b(FireFlyTallGrassBlock.java:33) ~[?:1.0.0.0] {re:classloading}
	at net.minecraft.block.Block.func_196265_a(Block.java:434) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_196944_b(BlockState.java:258) ~[?:?] {re:classloading,xf:fml:forgeendertech:randomTickBlock}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:466) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:405) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$6433/1198065928.accept(Unknown Source) ~[?:?] {}
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) ~[fastutil-8.2.1.jar:?] {}
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) ~[guava-21.0.jar:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:366) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:335) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:309) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:83)
	at ladysnake.illuminations.entity.FireFlyEntity.func_70088_a(FireFlyEntity.java:64)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:192)
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:99)
	at ladysnake.illuminations.entity.LightOrbEntity.<init>(LightOrbEntity.java:18)
	at ladysnake.illuminations.entity.FireFlyEntity.<init>(FireFlyEntity.java:49)
	at ladysnake.illuminations.block.FireFlyBlockTick.tick(FireFlyBlockTick.java:36)
	at ladysnake.illuminations.block.FireFlyTallGrassBlock.func_196267_b(FireFlyTallGrassBlock.java:33)
	at net.minecraft.block.Block.func_196265_a(Block.java:434)
	at net.minecraft.block.BlockState.func_196944_b(BlockState.java:258)
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:466)
	at net.minecraft.world.server.ServerChunkProvider.func_223434_a(SourceFile:405)
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$6433/1198065928.accept(Unknown Source)
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:366)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:335)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:309)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Stormwind99'/274, l='Aleod', x=155.50, y=70.00, z=237.26]]
	Chunk stats: ServerChunkCache: 3721
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Aleod
	Level seed: 7576636670874475867
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (96,65,160), Chunk: (at 0,4,0 in 6,10; contains blocks 96,0,160 to 111,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 468228 game time, 468228 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 5529 (now: true), thunder time: 95735 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1604100272 bytes (1529 MB) / 4023386112 bytes (3837 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.4.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.4.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.4
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		doubledoors_1.14-2.0.jar Double Doors {doubledoors@2.0 DONE}
		ultra_amplified_mod-1.14.4-6.12.2.jar Ultra Amplified Mod {ultra_amplified_mod@1.14.4-6.12.2 DONE}
		webslinger-1.14.4-3.1.0.jar WebSlinger {webslinger@3.1.0 DONE}
		foodfunk-1.14.4-5.0.2.jar FoodFunk {foodfunk@5.0.2 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		enchantable-1.1.0-1.14.4.jar Enchantable {enchantable@1.1.0 DONE}
		extendedslabs-1.14.4-0.1.0-beta.jar Extended Slabs {extendedslabs@0.1.0-beta DONE}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 DONE}
		megamap-1.14.4-2.2.0.jar Mega Map {megamap@2.2.0 DONE}
		Glacia-14.4.1b.jar §9§lGlacia§r {greenapple_glacia@§914.4.1b§r DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		bloomful-1.2.4.jar Bloomful {bloomful@1.2.3 DONE}
		CTD-Core-1.14.4-2.0.5b.jar CTD Core {ctdcore@2.0.5b DONE}
		FloristV1.1.4.jar Florist {florist@1.1.4 DONE}
		ForgeEndertech-1.14.4-5.2.2.0-build.0082.jar Forge Endertech {forgeendertech@5.2.2.0 DONE}
		BetterTitleScreen-1.14.4-1.7.jar Better Title Screen {bettertitlescreen@1.14.4-1.7 DONE}
		Controlling-5.0.7.jar Controlling {controlling@5.0.6 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		pantography-1.14.4-3.3.0.jar Pantography {pantography@3.3.0 DONE}
		NaturesCompass-1.14.4-1.8.5.jar Nature's Compass {naturescompass@1.14.4-1.8.5 DONE}
		cannycomposter-1.14.4-2.1.0.jar Canny Composter {cannycomposter@2.1.0 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		decorative_blocks_6b.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		DungeonCrawl-1.14.4-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		betteranimalsplus-1.14.4-9.0.0.jar Better Animals Plus {betteranimalsplus@9.0.0 DONE}
		BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 DONE}
		wumpleutil-1.14.4-3.5.0.jar Wumple Util Library {wumpleutil@3.5.0 DONE}
		RealisticTorches-1.14.4-3.0.0.jar Realistic Torches {realistictorches@1.14.4-3.0.0 DONE}
		Customized-Dungeon-Loot-1.14.x-(v.2.0.0).jar Customized Dungeon Loot {cdl@2.0.0 DONE}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		saplingstosticks-1.14.4-1.0.0.jar Saplings To Sticks {saplingstosticks@1.0.0 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		SnowRealMagic-1.14.4-1.5.2.jar Snow! Real Magic! {snowrealmagic@1.5.2 DONE}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 DONE}
		CarryOn MC1.14.4 v1.12.4.jar Carry On {carryon@1.12.4 DONE}
		endercompass-1.1.jar Ender Compass {endercompass@1.1 DONE}
		campfiretorches-1.14.4-1.0.3.jar Campfire Torches {campfiretorches@1.14.4-1.0.3 DONE}
		forge-1.14.4-28.2.4-universal.jar Forge {forge@28.2.4 DONE}
		winterdecorations-1.0.1.jar Winter Decorations {winterdecorations@1.0.1 DONE}
		Mo-Glowstone-1.14.4-2.0.4.jar Mo' Glowstone {moglowstone@2.0.5 DONE}
		ConsoleExperience-v1.5.1-1.14.4.jar Console Experience {consoleexperience@1.5.1 DONE}
		forge-1.14.4-28.2.4-client.jar Minecraft {minecraft@1.14.4 DONE}
		EnchantmentDescriptions-1.14.4-1.3.13.jar EnchantmentDescriptions {enchdesc@1.3.13 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		illuminations-0.1.0-1.14.4.jar Illuminations for Forge {illuminations@1.0.0.0 DONE}
		NaturalProgression-1.14.4-1.3.0b.jar Natural Progression {natural-progression@1.3.0b DONE}
		UndergroundBiomes-1.14.4-1.0-53.jar Underground Biomes {undergroundbiomes@1.0-53 DONE}
		Swamp_1.14.4_1.1.jar Better Swamplands Mod {swampland@1.14.4_1.0 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		baubles-1.6.1-1.14.4.jar Baubles {baubles@1.6.1 DONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 DONE}
		simplefarming-1.14.4-1.2.8.jar Simple Farming {simplefarming@1.14.4-1.2.8 DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		fairylights-2.1.15-1.14.4.jar Fairy Lights {fairylights@2.1.15 DONE}
		goprone-1.14.x-1.1.0.jar GoProne {goprone@1.14.x-1.1.0 DONE}
		palimpsest-1.14.4-1.3.1.jar Palimpsest {palimpsest@1.3.1 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		Inspirations-1.14.4-1.0.2.jar Inspirations {inspirations@1.14.4-1.0.2 DONE}
		simplegrinder-1.0.jar Simple Grinder {simplegrinder@1.14.4-a0.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		TorchBandolier-1.14.4-1.3.2+7.jar Torch Bandolier {torchbandolier@1.3.2+7 DONE}
		StorageDrawers-1.14.4-6.0.7.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		sit-1.14.4-v1.3.jar Sit {sit@v1.3 DONE}
		Animalium-0.4.1.jar Animalium {animalium@0.4.1 DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		immersivelighting-1.14-1.2.0.jar Immersive Lighting {immersivelighting@1.2.0 DONE}
		AmbientEnvironment-2.0.1.jar Ambient Environment {ambientenvironment@2.0.1 DONE}
		Menacing Monsters 1.3.3.jar Menacing Monsters {menacing_monsters@1.3.3 DONE}
		mcw-furniture-1.0.1-mc1.14.4.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		earthsanimals-1.14.4-0.0.4-beta.jar Earth's Animals {earthsanimals@1.14.4-0.0.4-beta DONE}
		AdChimneys-1.14.4-4.0.0.1-build.0072.jar Advanced Chimneys {adchimneys@4.0.0.1 DONE}
		BetterBurning-1.14.4-1.0.1.jar BetterBurning {betterburning@1.0.1 DONE}
		instantunify-1.14.4-1.0.3.jar InstantUnify {instantunify@1.0.3 DONE}
		xptome-1.14.4-v1.1.4.jar XP Tome {xpbook@v1.1.4 DONE}
		flourishingfoliage-1.14.4-2.2.0.jar Flourishing Foliage {flourishingfoliage@2.2.0 DONE}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 DONE}
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)

	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['Stormwind99'/274, l='Aleod', x=155.50, y=70.00, z=237.26]]
	Data Packs: vanilla, mod:adchimneys, mod:ambientenvironment, mod:ambientsounds, mod:animalium, mod:arl, mod:attributefix, mod:baubles, mod:betteradvancements (incompatible), mod:betteranimalsplus, mod:betteranimationscollection2, mod:betterburning, mod:bettertitlescreen, mod:biomesoplenty, mod:bloomful, mod:campfiretorches, mod:cannycomposter, mod:carryon, mod:cdl, mod:consoleexperience, mod:controlling, mod:ctdcore, mod:d2p, mod:decorative_blocks, mod:ding, mod:doubledoors, mod:dungeoncrawl, mod:earthsanimals, mod:enchantable, mod:enchdesc, mod:endercompass, mod:extcaves, mod:extendedslabs, mod:fairylights, mod:florist, mod:flourishingfoliage, mod:foodfunk, mod:forge, mod:forgeendertech, mod:goprone, mod:greenapple_glacia, mod:illuminations, mod:immersivelighting, mod:inspirations, mod:instantunify, mod:jei, mod:kiwi, mod:mantle, mod:mcwfurnitures, mod:megamap, mod:menacing_monsters, mod:moglowstone, mod:natural-progression, mod:naturescompass, mod:palimpsest, mod:pantography, mod:placebo, mod:quark, mod:realistictorches, mod:sereneseasons, mod:silentlib, mod:simplefarming, mod:simplegrinder, mod:sit, mod:snowrealmagic, mod:storagedrawers, mod:swampland, mod:toastcontrol, mod:torchbandolier, mod:ultra_amplified_mod, mod:undergroundbiomes, mod:upgrade_aquatic, mod:waddles, mod:waila, mod:webslinger, mod:winterdecorations, mod:wumpleutil, mod:xpbook, mod:saplingstosticks
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by cdevine-xom** [comment]
I can confirm this happens to me too. It seems likely to be an incompatibility with Quark.
